set(_CATKIN_CURRENT_PACKAGE "pi_nodes")
set(pi_nodes_VERSION "0.0.0")
set(pi_nodes_MAINTAINER "michael <michael@todo.todo>")
set(pi_nodes_PACKAGE_FORMAT "2")
set(pi_nodes_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(pi_nodes_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(pi_nodes_BUILDTOOL_DEPENDS "catkin")
set(pi_nodes_BUILDTOOL_EXPORT_DEPENDS )
set(pi_nodes_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(pi_nodes_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(pi_nodes_TEST_DEPENDS )
set(pi_nodes_DOC_DEPENDS )
set(pi_nodes_URL_WEBSITE "")
set(pi_nodes_URL_BUGTRACKER "")
set(pi_nodes_URL_REPOSITORY "")
set(pi_nodes_DEPRECATED "")