authors: []
blacklist: []
build_space: build_cb
catkin_make_args: []
cmake_args: []
devel_layout: linked
devel_space: devel_cb
extend_path: null
extends: null
install: true
install_space: install_cb
isolate_install: false
jobs_args: []
licenses:
- TODO
log_space: logs_cb
maintainers: []
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
