set(_CATKIN_CURRENT_PACKAGE "base_nodes")
set(base_nodes_VERSION "0.0.0")
set(base_nodes_MAINTAINER "vboxuser <vboxuser@todo.todo>")
set(base_nodes_PACKAGE_FORMAT "2")
set(base_nodes_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(base_nodes_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(base_nodes_BUILDTOOL_DEPENDS "catkin")
set(base_nodes_BUILDTOOL_EXPORT_DEPENDS )
set(base_nodes_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(base_nodes_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(base_nodes_TEST_DEPENDS )
set(base_nodes_DOC_DEPENDS )
set(base_nodes_URL_WEBSITE "")
set(base_nodes_URL_BUGTRACKER "")
set(base_nodes_URL_REPOSITORY "")
set(base_nodes_DEPRECATED "")